### ISSUE TITLE
２つのファイルのI/Oの途中で障害が発生した場合の影響をどの程度考慮するか

### ISSUE THREAD

**Issue by ukishima** [wagumi/5000#4]
https://github.com/wagumi/5000/blob/d1be70066ef0fa9905111d4fc48d1bb68d0801e5/server.js#L110-L111

配布用のURLを管理するlist.txtと、使用済みのURLと受け取ったユーザーを管理するminted.jsonの両者を更新するここのタイミングで予期せぬ障害が発生し片方だけが更新されるとデータに矛盾が生じます。
そこへの対応のためにreset_userコマンドを用意し、基本的には大きな問題にはならないと想定していますが、このリスクをどの程度考慮しますか。

**Comment by tksohishi** [comment]
mitigation措置も用意されてあるのでそこまで真面目に対応する必要はなさそうな気がしますね。

**Comment by ukishima** [comment]
> mitigation措置も用意されてあるのでそこまで真面目に対応する必要はなさそうな気がしますね。

ありがとうございます。
自分もそのように考えて今の実装に至っているわけですが、ズレが発生する可能性を許容するコンセンサスはとっておきたいと思っています。

**Comment by ukishima** [comment]
この問題は発生確率とその影響度合を考慮し、許容するものとします。
